In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import date 
import time
df = pd.read_csv("superstore_excel-selected-columns.csv")

In [10]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders
...,...,...,...,...,...,...,...,...,...,...
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [3]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders

In [4]:
df.tail()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [5]:
df.shape

(5000, 10)

In [7]:
df.dtypes

Order ID         str
Order Date       str
Ship Date        str
Ship Mode        str
Customer ID      str
Customer Name    str
Segment          str
Region           str
Category         str
Sub-Category     str
dtype: object

In [8]:
df.shape[0]  #for row

5000

In [9]:
df.shape[1] # for columns

10

In [11]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Region', 'Category', 'Sub-Category'],
      dtype='str')

In [15]:
df.isnull().sum

<bound method DataFrame.sum of       Order ID  Order Date  Ship Date  Ship Mode  Customer ID  Customer Name  \
0        False       False      False      False        False          False
1        False       False      False      False        False          False
2        False       False      False      False        False          False
3        False       False      False      False        False          False
4        False       False      False      False        False          False
...        ...         ...        ...        ...          ...            ...
4995     False       False      False      False        False          False
4996     False       False      False      False        False          False
4997     False       False      False      False        False          False
4998     False       False      False      False        False          False
4999     False       False      False      False        False          False

      Segment  Region  Category  Sub-Category
0       False   False     False         False
1       False   False     False         False
2       False   False     False         False
3       False   False     False         False
4       False   False     False         False
...       ...     ...       ...           ...
4995    False   False     False         False
4996    False   False     False         False
4997    False   False     False         False
4998    False   False     False         False
4999    False   False     False         False

[5000 rows x 10 columns]>

In [19]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [18]:
df["Ship Mode"].value_counts()

Ship Mode
Second Class      1305
Same Day          1245
Standard Class    1234
First Class       1216
Name: count, dtype: int64

In [22]:
df["Segment"].value_counts()

Segment
Corporate      1686
Home Office    1683
Consumer       1631
Name: count, dtype: int64

In [24]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders
...,...,...,...,...,...,...,...,...,...,...
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs

In [25]:
df["Category"].value_counts().head(10)

Category
Furniture          1670
Office Supplies    1668
Technology         1662
Name: count, dtype: int64

In [26]:
df["Sub-Category"].value_counts().head(10)

Sub-Category
Chairs         447
Tables         418
Furnishings    409
Bookcases      396
Copiers        361
Binders        358
Labels         355
Accessories    345
Phones         339
Paper          334
Name: count, dtype: int64

In [28]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Region', 'Category', 'Sub-Category'],
      dtype='str')

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"],errors="coerce")
od_year=df["Order Date"].dt.year.dropna().to_numpy() 

od_year

array([2024, 2023, 2024, ..., 2024, 2024, 2024],
      shape=(5000,), dtype=int32)

In [48]:
np.mean(od_year)

np.float64(2023.7718)

In [49]:
np.min(od_year)

np.int32(2023)

In [38]:
np.max(od_year)

np.int32(2025)

In [39]:

np.std(od_year)

np.float64(0.6709133774191718)

In [50]:
df["Order Date"].isna().sum()

np.int64(0)

In [64]:
df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors="coerce")

df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

display(df[["Order Date", "Ship Date", "Order Year", "Order Month", "Shipping Days"]].head())

  Order Date  Ship Date  Order Year  Order Month  Shipping Days
0 2024-10-06 2025-05-01        2024           10            207
1 2023-06-12 2025-05-05        2023            6            693
2 2024-04-18 2025-04-24        2024            4            371
3 2023-11-02 2025-05-07        2023           11            552
4 2023-07-15 2025-04-14        2023            7            639

In [65]:
df.dtypes["Order Date"]

dtype('<M8[us]')